name: 'user_service'

services:
  
  domic.user.api:
    networks:
      - domic
    image: user_service_api_image:1.0.0
    container_name: "user_service_api"
#    deploy:
#      replicas: 3
#      resources:
#        limits:
#          memory: 150M
#        reservations:
#          memory: 150M
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "1160-1180:443"
    volumes:
      - log:/app/CoreLogs
      - ~\.aspnet\https\:/https/
    environment:
      - Elastic-Host=http://domic.elastic.search:9200
      - Elastic-Index=user
      - Elastic-Username=domic
      - Elastic-Password=Domic123!@#
      - E-RabbitMQ-Host=domic.rabbit.mq
      - E-RabbitMQ-Port=5672
      - E-RabbitMQ-Username=domic
      - E-RabbitMQ-Password=Domic123!@#
      - I-RabbitMQ-Host=domic.user.rabbit.mq
      - I-RabbitMQ-Port=5672
      - I-RabbitMQ-Username=domic
      - I-RabbitMQ-Password=Domic123!@#
      - E-RedisConnectionString=domic.redis:6379
      - I-RedisConnectionString=domic.user.redis:6379
      - MongoConnectionString=
      - C-SqlServerConnectionString=Server=domic.user.command.sql.server,1433;Database=UserService;User ID=sa;Password=Domic123!@#;Persist Security Info=True;MultipleActiveResultSets=True;
      - Q-SqlServerConnectionString=Server=domic.user.query.sql.server,1433;Database=UserService;User ID=sa;Password=Domic123!@#;Persist Security Info=True;MultipleActiveResultSets=True;
      - Host=domic.user.api
      - Port=443
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Domic123!@#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Domic.WebAPI.pfx
    depends_on:
      - domic.user.command.sql.server
      - domic.user.query.sql.server
      - domic.user.redis
      - domic.user.rabbit.mq
  
  domic.user.command.sql.server:
    networks:
      - domic
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'user_command_sql_server'
    restart: on-failure
    ports:
      - 1435:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Domic123!@#
  
  domic.user.query.sql.server:
    networks:
      - domic
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'user_query_sql_server'
    restart: on-failure
    ports:
      - 1400:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Domic123!@#
  
  domic.user.redis:
    networks:
      - domic
    image: 'redis'
    container_name: 'user_redis'
    command: 'redis-server'
    ports:
      - 3380:6379
  
  domic.user.rabbit.mq:
    networks:
      - domic
    image: 'rabbitmq:3-management'
    container_name: 'user_rabbit_mq'
    restart: on-failure
    ports:
      - '15660:15672'
      - '5660:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=domic
      - RABBITMQ_DEFAULT_PASS=Domic123!@#

volumes:
  log:
    
networks:
  domic:
    external: true